### post new message with all params
POST http://localhost:3001/api HTTP/1.1
content-type: application/json

{
    "message": "This is a test secret message",
    "password": "12345",
    "lifetime": 30000,
    "readLimit": 10
}

### without password
POST http://localhost:3001/api HTTP/1.1
content-type: application/json

{
    "message": "This is a test secret message without password",
    "lifetime": 1000000,
    "readLimit": 10
}

### only message
POST http://localhost:3001/api HTTP/1.1
content-type: application/json

{
    "message": "This is a test secret message without password or limits"
}

### only lifetime
POST http://localhost:3001/api HTTP/1.1
content-type: application/json

{
    "message": "This is a test secret message without password or limits",
    "lifetime": 45000
}

### only read limit
POST http://localhost:3001/api HTTP/1.1
content-type: application/json

{
    "message": "This is a test secret message without password or limits",
    "readLimit": 20
}

### get with password
GET http://localhost:3001/api/lTdVo3ZAPCSLQzajHg3v-z_nqtCX44 HTTP/1.1
content-type: application/json

{
    "password": "12345"
}

### get without password
GET http://localhost:3001/api/X8Kzz6iOIGuYRzrowZE0pcde4mb_wO HTTP/1.1